  version:  '3.7'
  services:
    mysql:
      image: mysql:5.7
      hostname: mysql
      volumes:
        - ./var/lib/mysql:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=practice
        - MYSQL_USER=root
        - MYSQL_ROOT_PASSWORD=123
      ports:
        - "3306:3306"
    adminer:
      image: adminer
      restart: on-failure
      ports:
        - "8080:8080"
    nginx:
      image: nginx:1.15.3-alpine
      restart: on-failure
      volumes:
        - './apps/my-symfony-app/public/:/usr/src/app'
        - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      ports:
        - "81:80"
      depends_on:
        - php
    php:
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      restart: on-failure
      volumes:
        - './apps/my-symfony-app/:/usr/src/app'
      ports:
        - "9000:9000"
      env_file:
        - .env
      user: 1000:1000